import { HCPCExpert } from './types';

export const UK_EXPERTS: HCPCExpert[] = [
  {
    id: "exp-alastair-wright",
    slug: "alastair-wright",
    fullName: "Alastair Wright",
    credentials: "BSc (Hons) Physiotherapy, MSc Adv Musculoskeletal, MCSP",
    hcpcNumber: "PH108942",
    cspNumber: "CSP 094812",
    specialties: ["Orthopaedic Spine", "Post-Op Knee/Hip", "Manual Therapy", "Chronic Pain"],
    languagesSpoken: ["English"],
    experienceYears: 14,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=800",
    citiesServed: ["London", "Westminster", "Kensington", "Chelsea", "Canary Wharf"],
    primaryHub: "Greater London",
    bio: "Former NHS Lead Musculoskeletal Specialist at Guy's and St Thomas' NHS Foundation Trust. Alastair specializes in complex lumbar disc pathology, spinal stenosis, and rapid rehabilitation following total joint arthroplasty.",
    clinicalFocus: ["Lumbar Disc Herniation", "Total Knee Replacement", "Cervical Radiculopathy", "Hip Resurfacing"]
  },
  {
    id: "exp-charlotte-sinclair",
    slug: "charlotte-sinclair",
    fullName: "Charlotte Sinclair",
    credentials: "BSc (Hons) Physiotherapy, MSc Sports Medicine, MCSP",
    hcpcNumber: "PH114298",
    cspNumber: "CSP 102384",
    specialties: ["Sports Rehabilitation", "ACL & Meniscus", "Rotator Cuff", "Concussion Protocols"],
    languagesSpoken: ["English", "French"],
    experienceYears: 11,
    imageUrl: "https://images.unsplash.com/photo-1594824813501-4835691c28c8?auto=format&fit=crop&q=80&w=800",
    citiesServed: ["London", "Richmond", "Wimbledon", "Hampstead", "Islington"],
    primaryHub: "Greater London",
    bio: "Consultant sports physiotherapist working with elite runners, tennis players, and CrossFit athletes. Charlotte integrates 3D video kinematics and progressive neuromuscular resistance loading for return-to-sport milestones.",
    clinicalFocus: ["ACL Reconstruction Phased Recovery", "Rotator Cuff Tears", "Meniscus Tears", "Ankle Syndesmosis"]
  },
  {
    id: "exp-james-callum",
    slug: "james-callum",
    fullName: "James Callum",
    credentials: "BSc (Hons) Physiotherapy, Dip Neurological Rehabilitation, MCSP",
    hcpcNumber: "PH097431",
    cspNumber: "CSP 088921",
    specialties: ["Neurological Rehab", "Stroke Recovery", "Parkinson's Mobility", "Vestibular Therapy"],
    languagesSpoken: ["English"],
    experienceYears: 16,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=800",
    citiesServed: ["Manchester", "Salford", "Didsbury", "Altrincham", "Wilmslow"],
    primaryHub: "Greater Manchester",
    bio: "Specialist neurological physiotherapist trained in Bobath techniques and motor relearning. James delivers structured home recovery programs for patients stepping down from acute hospital stroke units.",
    clinicalFocus: ["Post-Stroke Hemiparesis", "Parkinson's Disease Gait Training", "Multiple Sclerosis", "Vestibular Balance"]
  },
  {
    id: "exp-fiona-macdougall",
    slug: "fiona-macdougall",
    fullName: "Fiona MacDougall",
    credentials: "BSc (Hons) Physiotherapy, PGCert Pelvic Health, MCSP",
    hcpcNumber: "PH120485",
    cspNumber: "CSP 115902",
    specialties: ["Pelvic Floor Physiotherapy", "Post-Natal Diastasis", "Core Stability", "Orthopaedics"],
    languagesSpoken: ["English"],
    experienceYears: 9,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=800",
    citiesServed: ["Edinburgh", "Leith", "Stockbridge", "Morningside", "West End"],
    primaryHub: "Edinburgh & Lothians",
    bio: "Specialized in advanced pelvic floor muscle assessment, pre/post-natal functional restoration, and core kinetic chain retraining throughout Scotland's central belt.",
    clinicalFocus: ["Pelvic Organ Prolapse", "Diastasis Recti", "Urinary Incontinence", "Sacroiliac Joint Dysfunction"]
  },
  {
    id: "exp-edward-davies",
    slug: "edward-davies",
    fullName: "Edward Davies",
    credentials: "BSc (Hons) Physiotherapy, MSc Orthopaedic Manual Therapy, MCSP",
    hcpcNumber: "PH103274",
    cspNumber: "CSP 098451",
    specialties: ["Seniors Fall Prevention", "Geriatric Mobility", "Spine Care", "Ergonomics"],
    languagesSpoken: ["English", "Welsh"],
    experienceYears: 13,
    imageUrl: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=800",
    citiesServed: ["Cardiff", "Penarth", "Pontcanna", "Bristol", "Bath"],
    primaryHub: "Cardiff & South Wales",
    bio: "Bilingual Chartered Physiotherapist dedicated to home environment safety audits, balance conditioning, and active strength building for older adults across South Wales and the West Country.",
    clinicalFocus: ["Vestibular Fall Prevention", "Gait Stability", "Osteoarthritis Joint Care", "Post-Hip Fracture Rehab"]
  }
];
