import { TherapistCard } from '@/types/therapist';

const DEFAULT_AVATAR = '/images/aries-emblem.png';

export const VERIFIED_THERAPISTS_CATALOG: TherapistCard[] = [
  {
    id: 'th-1',
    slug: 'dr-kajal-vora',
    name: 'Dr. Kajal Vora, PT',
    qualification: 'MPT (Neurology), BPT, MIAP',
    specialization: 'Neurology',
    experience: '12 Years',
    city: 'Mumbai',
    state: 'Maharashtra',
    areas: ['Colaba', 'Cuffe Parade', 'Marine Drive', 'Worli', 'Bandra West', 'Lower Parel', 'Borivali West'],
    rating: 4.9,
    reviewCount: 128,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Hindi', 'Gujarati', 'Marathi'],
    services: ['Neuro Rehabilitation', 'Stroke Recovery', 'Parkinson Care', 'Geriatric Rehab'],
    bio: 'Senior consultant neuro-physiotherapist with over 12 years of clinical experience in home-based stroke recovery, neuromuscular facilitation, and post-brain trauma functional restoration.',
    isVerified: true,
    education: ['Master of Physiotherapy (Neurology) - MUHS', 'Bachelor of Physiotherapy - KEM Hospital Mumbai'],
    feedback: [
      { rating: 5, comment: 'Dr. Kajal transformed my father recovery after stroke. Extremely patient and competent.', user: 'Rohan Mehta' },
      { rating: 5, comment: 'Remarkable improvement in mobility within 3 weeks of home visits.', user: 'Ananya S.' },
    ],
  },
  {
    id: 'th-2',
    slug: 'dr-twinkle-patel',
    name: 'Dr. Twinkle Patel, PT',
    qualification: 'BPT, MIAP, Certified Manual Therapist',
    specialization: 'Orthopedics',
    experience: '10 Years',
    city: 'Mumbai',
    state: 'Maharashtra',
    areas: ['Andheri West', 'Lokhandwala', 'Juhu', 'Powai', 'Goregaon', 'Bandra East', 'Borivali West'],
    rating: 4.8,
    reviewCount: 96,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Hindi', 'Gujarati'],
    services: ['Orthopedic Rehab', 'Spine & Joint Mobilization', 'Frozen Shoulder', 'Knee Replacement Care'],
    bio: 'Specialist in orthopedic rehabilitation and biomechanical alignment, focusing on rapid pain relief and long-term functional stability for joint and spine conditions.',
    isVerified: true,
    education: ['Bachelor of Physiotherapy - DY Patil Medical College', 'Certification in Mulligan Concept & Dry Needling'],
    feedback: [
      { rating: 5, comment: 'Relieved my severe frozen shoulder pain when other treatments failed.', user: 'Kavita Desai' },
    ],
  },
  {
    id: 'th-3',
    slug: 'dr-sam-evans',
    name: 'Dr. Sam Evans, PT',
    qualification: 'MPT (Sports Medicine), CSCS',
    specialization: 'Sports',
    experience: '15 Years',
    city: 'Delhi',
    state: 'Delhi',
    areas: ['South Delhi', 'Vasant Vihar', 'Greater Kailash', 'Golf Course Road', 'Gurugram', 'Cyber City'],
    rating: 4.9,
    reviewCount: 142,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Hindi', 'Punjabi'],
    services: ['Sports Injury Management', 'ACL Recovery Protocol', 'Kinesio Taping', 'Dry Needling'],
    bio: 'Renowned sports physiotherapist and athletic conditioning coach with over 15 years treating elite athletes, marathoners, and post-arthroscopic knee/shoulder patients.',
    isVerified: true,
    education: ['MPT in Sports Physiotherapy - Jamia Hamdard', 'Certified Strength and Conditioning Specialist (CSCS)'],
    feedback: [
      { rating: 5, comment: 'Returned to marathon running 4 months after ACL surgery thanks to Dr. Sam protocol.', user: 'Vikram Grover' },
    ],
  },
  {
    id: 'th-4',
    slug: 'dr-chloe-davis',
    name: 'Dr. Chloe Davis, PT',
    qualification: 'MPT (Musculoskeletal Disorders), CMP',
    specialization: 'Pain Management',
    experience: '8 Years',
    city: 'Bengaluru',
    state: 'Karnataka',
    areas: ['Indiranagar', 'Koramangala', 'HSR Layout', 'Whitefield', 'Bellandur', 'JP Nagar'],
    rating: 4.9,
    reviewCount: 88,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Kannada', 'Hindi', 'Tamil'],
    services: ['Chronic Back Pain Protocol', 'Ergonomic Corrections', 'Myofascial Release', 'Posture Rehab'],
    bio: 'Dedicated spine and chronic pain rehabilitation specialist helping tech professionals and corporate leaders eliminate debilitating neck, shoulder, and lumbar strain.',
    isVerified: true,
    education: ['MPT in Musculoskeletal Sciences - Rajiv Gandhi University of Health Sciences'],
    feedback: [
      { rating: 5, comment: 'Chronic desk-job sciatica completely disappeared after 6 sessions.', user: 'Deepak Rao' },
    ],
  },
  {
    id: 'th-5',
    slug: 'dr-rajesh-sharma',
    name: 'Dr. Rajesh Sharma, PT',
    qualification: 'MPT (Cardio-Respiratory & ICU Rehab), BPT',
    specialization: 'Geriatrics',
    experience: '14 Years',
    city: 'Pune',
    state: 'Maharashtra',
    areas: ['Koregaon Park', 'Baner', 'Aundh', 'Viman Nagar', 'Kothrud', 'Kalyani Nagar'],
    rating: 4.9,
    reviewCount: 110,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Hindi', 'Marathi'],
    services: ['Geriatric Mobility', 'Post-ICU Respiratory Rehab', 'Balance & Fall Prevention', 'Bedridden Care'],
    bio: 'Senior consultant specializing in elderly mobility preservation, chest physiotherapy, and compassionate home rehabilitation for bedridden and frail seniors.',
    isVerified: true,
    education: ['MPT (Cardiorespiratory) - Pune University', 'BPT - Sancheti Institute'],
    feedback: [
      { rating: 5, comment: 'My 82-year-old grandmother was able to walk independently again.', user: 'Pooja Kulkarni' },
    ],
  },
  {
    id: 'th-6',
    slug: 'dr-ananya-roy',
    name: 'Dr. Ananya Roy, PT',
    qualification: 'MPT (Pediatric Physiotherapy)',
    specialization: 'Pediatrics',
    experience: '9 Years',
    city: 'Kolkata',
    state: 'West Bengal',
    areas: ['Salt Lake', 'Alipore', 'New Town', 'Ballygunge', 'Park Street', 'Gariahat'],
    rating: 4.8,
    reviewCount: 78,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Bengali', 'Hindi'],
    services: ['Cerebral Palsy Therapy', 'Developmental Delay Care', 'Sensory Integration', 'Torticollis Care'],
    bio: 'Compassionate pediatric physical therapist helping infants and young children overcome congenital, neurological, and developmental milestones challenges.',
    isVerified: true,
    education: ['MPT Pediatrics - NILD Kolkata', 'BPT - West Bengal University of Health Sciences'],
    feedback: [
      { rating: 5, comment: 'Incredible patience and play-based therapy with our 4-year-old son.', user: 'Siddhartha Sen' },
    ],
  },
  {
    id: 'th-7',
    slug: 'dr-vikramaditya-reddy',
    name: 'Dr. Vikramaditya Reddy, PT',
    qualification: 'MPT (Orthopedics & Sports Rehab)',
    specialization: 'Orthopedics',
    experience: '11 Years',
    city: 'Hyderabad',
    state: 'Telangana',
    areas: ['Jubilee Hills', 'Banjara Hills', 'Gachibowli', 'HITEC City', 'Madhapur', 'Kondapur'],
    rating: 4.9,
    reviewCount: 105,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Telugu', 'Hindi'],
    services: ['Joint Replacement Rehab', 'Post-Fracture Mobilization', 'Spine Traction', 'Sciatica Care'],
    bio: 'Orthopedic rehabilitation consultant specialized in post-TKR/THR rapid recovery protocols and high-precision spine biomechanics.',
    isVerified: true,
    education: ['MPT Ortho - Osmania Medical College', 'Fellowship in Manual Therapy'],
    feedback: [
      { rating: 5, comment: 'Doctor Reddy got me walking without support 10 days after knee surgery.', user: 'Srinivas V.' },
    ],
  },
  {
    id: 'th-8',
    slug: 'dr-priya-sundaram',
    name: 'Dr. Priya Sundaram, PT',
    qualification: 'BPT, MPT (Women Health), CMP',
    specialization: "Women's Health",
    experience: '13 Years',
    city: 'Chennai',
    state: 'Tamil Nadu',
    areas: ['Anna Nagar', 'Adyar', 'Boat Club', 'OMR', 'Nungambakkam', 'Besant Nagar'],
    rating: 4.9,
    reviewCount: 115,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Tamil', 'Hindi'],
    services: ['Antenatal & Postnatal Rehab', 'Pelvic Floor Therapy', 'Diastasis Recti Repair', 'Urinary Incontinence'],
    bio: "Pioneering clinical lead in women's pelvic health, prenatal conditioning, and postpartum recovery empowering mothers to regain structural stability and core vitality.",
    isVerified: true,
    education: ['MPT Women Health - Sri Ramachandra University', 'Certified Pelvic Floor Practitioner'],
    feedback: [
      { rating: 5, comment: 'Transformative postpartum recovery care in the comfort of my home.', user: 'Meenakshi R.' },
    ],
  },
  {
    id: 'th-9',
    slug: 'dr-hardik-shah',
    name: 'Dr. Hardik Shah, PT',
    qualification: 'MPT (Neurology & Geriatrics)',
    specialization: 'Neurology',
    experience: '10 Years',
    city: 'Ahmedabad',
    state: 'Gujarat',
    areas: ['SG Highway', 'Prahlad Nagar', 'Bodakdev', 'Satellite', 'Vastrapur', 'Thaltej'],
    rating: 4.8,
    reviewCount: 92,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Gujarati', 'Hindi'],
    services: ['Stroke Rehabilitation', 'Parkinsons Movement Therapy', 'Gait & Balance Labs', 'Neuropathy Care'],
    bio: 'Neurological rehabilitation specialist dedicated to restoring independence, gait equilibrium, and motor neural pathways for patients recovering from neuro ailments.',
    isVerified: true,
    education: ['MPT Neurology - Gujarat University', 'Certified PNF Practitioner'],
    feedback: [
      { rating: 5, comment: 'Helped my father regain balance and confidence to walk outdoors.', user: 'Jignesh Patel' },
    ],
  },
  {
    id: 'th-10',
    slug: 'dr-neha-kulkarni',
    name: 'Dr. Neha Kulkarni, PT',
    qualification: 'MPT (Musculoskeletal & Orthopedics), BPT',
    specialization: 'Orthopedics',
    experience: '11 Years',
    city: 'Thane',
    state: 'Maharashtra',
    areas: ['Thane', 'Thane West', 'Thane East', 'Ghodbunder Road', 'Majiwada', 'Vasant Vihar', 'Hiranandani Estate', 'Naupada', 'Panchpakhadi', 'Manpada', 'Wagle Estate', 'Kalyan', 'Dombivli'],
    rating: 4.9,
    reviewCount: 118,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Marathi', 'Hindi'],
    services: ['Orthopedic Rehabilitation', 'Spine & Posture Ergonomics', 'Post-Op Knee Rehab', 'Sciatica Relief'],
    bio: 'Renowned orthopedic and musculoskeletal rehabilitation consultant in Thane, delivering structured evidence-based physical therapy for spinal conditions, joint arthritis, and surgical recovery.',
    isVerified: true,
    education: ['MPT Orthopedics - MUHS Nashik', 'BPT - Topiwala National Medical College'],
    feedback: [
      { rating: 5, comment: 'Dr. Neha home visits in Ghodbunder Road cured my lumbar disc pain completely.', user: 'Manish Sawant' },
    ],
  },
  {
    id: 'th-11',
    slug: 'dr-amit-deshmukh',
    name: 'Dr. Amit Deshmukh, PT',
    qualification: 'MPT (Neurology & Stroke Mobility), BPT',
    specialization: 'Neurology',
    experience: '9 Years',
    city: 'Thane',
    state: 'Maharashtra',
    areas: ['Thane', 'Thane West', 'Ghodbunder Road', 'Kolshet', 'Balkum', 'Vartak Nagar', 'Kalwa', 'Mumbra', 'Diva', 'Kalyan'],
    rating: 4.8,
    reviewCount: 84,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Marathi', 'Hindi'],
    services: ['Neuro Rehabilitation', 'Stroke Mobility Protocols', 'Parkinsons Movement Therapy', 'Balance Labs'],
    bio: 'Dedicated neuro-physiotherapy clinician serving families across Thane and central suburbs with state-of-the-art motor retraining and gait rehabilitation.',
    isVerified: true,
    education: ['MPT Neurology - MGM Institute of Health Sciences', 'BPT - MUHS'],
    feedback: [
      { rating: 5, comment: 'Exceptional neuro therapy support in Majiwada for post-stroke recovery.', user: 'Suresh Patil' },
    ],
  },
  {
    id: 'th-12',
    slug: 'dr-rohit-shinde',
    name: 'Dr. Rohit Shinde, PT',
    qualification: 'MPT (Sports & Manual Therapy), CSCS',
    specialization: 'Sports',
    experience: '12 Years',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    areas: ['Navi Mumbai', 'Vashi', 'Nerul', 'Kharghar', 'Seawoods', 'CBD Belapur', 'Sanpada', 'Panvel', 'Airoli', 'Kopar Khairane'],
    rating: 4.9,
    reviewCount: 102,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Marathi', 'Hindi'],
    services: ['Sports Injury Care', 'ACL Rehabilitation', 'Manual Therapy', 'Myofascial Release'],
    bio: 'Senior sports physiotherapist and certified manual therapist providing elite clinical recovery across Navi Mumbai nodes from Vashi to Kharghar.',
    isVerified: true,
    education: ['MPT Sports - DY Patil University Navi Mumbai', 'Certified Mulligan Practitioner'],
    feedback: [
      { rating: 5, comment: 'Back on the football turf after ligament tear in just 8 weeks of therapy.', user: 'Aditya K.' },
    ],
  },
  {
    id: 'th-13',
    slug: 'dr-sneha-verma',
    name: 'Dr. Sneha Verma, PT',
    qualification: 'MPT (Orthopedics & Joint Mobilization)',
    specialization: 'Orthopedics',
    experience: '10 Years',
    city: 'Surat',
    state: 'Gujarat',
    areas: ['Surat', 'Adajan', 'Vesu', 'Piplod', 'Ghod Dod Road', 'Varachha', 'Pal', 'Rander', 'City Light'],
    rating: 4.8,
    reviewCount: 76,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Gujarati', 'Hindi'],
    services: ['Joint Replacement Rehab', 'Frozen Shoulder Mobilization', 'Neck & Back Spine Care', 'Geriatric Rehab'],
    bio: 'Leading clinical physiotherapist in Surat delivering personalized doorstep rehabilitation and advanced electrotherapy across Adajan, Vesu, and Piplod.',
    isVerified: true,
    education: ['MPT Orthopedics - Veer Narmad South Gujarat University', 'BPT - Government Physiotherapy College'],
    feedback: [
      { rating: 5, comment: 'Dr. Sneha provides the best home physiotherapy service in Vesu, Surat.', user: 'Pravin Shah' },
    ],
  },
  {
    id: 'th-14',
    slug: 'dr-gaurav-chopra',
    name: 'Dr. Gaurav Chopra, PT',
    qualification: 'MPT (Sports & Musculoskeletal), CMP',
    specialization: 'Sports',
    experience: '14 Years',
    city: 'Gurugram',
    state: 'Haryana',
    areas: ['Gurugram', 'Gurgaon', 'DLF Phase 1-5', 'Golf Course Road', 'Sohna Road', 'Cyber Hub', 'Sector 56', 'Sector 57', 'Sector 14', 'Sector 49'],
    rating: 4.9,
    reviewCount: 135,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Hindi', 'Punjabi'],
    services: ['Spine & Posture Rehab', 'Sports Performance Recovery', 'Dry Needling', 'Ergonomic Consultations'],
    bio: 'Lead consultant physical therapist in Millennium City Gurugram specialized in corporate ergonomic health, spine decompression, and athletic conditioning.',
    isVerified: true,
    education: ['MPT Sports - Manipal University', 'Certified Maitland Manual Therapist'],
    feedback: [
      { rating: 5, comment: 'Complete relief from chronic cervical spine pain on Golf Course Road.', user: 'Neeraj Arora' },
    ],
  },
  {
    id: 'th-15',
    slug: 'dr-ritu-malhotra',
    name: 'Dr. Ritu Malhotra, PT',
    qualification: 'MPT (Cardiopulmonary & Elderly Care), BPT',
    specialization: 'Geriatrics',
    experience: '11 Years',
    city: 'Noida',
    state: 'Uttar Pradesh',
    areas: ['Noida', 'Sector 62', 'Sector 18', 'Sector 50', 'Sector 137', 'Greater Noida', 'Indirapuram', 'Sector 76', 'Sector 128'],
    rating: 4.9,
    reviewCount: 98,
    imageUrl: DEFAULT_AVATAR,
    isAvailable: true,
    languages: ['English', 'Hindi'],
    services: ['Elderly Fall Prevention', 'Chest & Respiratory Physio', 'Post-Op Knee Care', 'Bedridden Patient Care'],
    bio: 'Dedicated physical therapist in Noida providing compassionate geriatric care, respiratory rehabilitation, and functional independence restoration.',
    isVerified: true,
    education: ['MPT Cardiopulmonary - Jamia Millia Islamia', 'BPT - Sharda University'],
    feedback: [
      { rating: 5, comment: 'Dr. Ritu helped my mother recover smoothly after hip replacement in Sector 50.', user: 'Alok Gupta' },
    ],
  },
];
