import { TherapistCard } from '@/types/therapist';

const DEFAULT_AVATAR = '/images/aries-emblem.png';

export const VERIFIED_THERAPISTS_CATALOG: TherapistCard[] = [
  {
    id: 'th-uk-1',
    slug: 'mr-alastair-wright',
    name: 'Mr. Alastair Wright, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Sports & Musculoskeletal',
    experience: '15 Years',
    city: 'London',
    state: 'Greater London',
    areas: ['Canary Wharf', 'Westminster', 'City of London', 'Kensington', 'Chelsea', 'Mayfair', 'Camden', 'Islington'],
    rating: 4.9,
    reviewCount: 142,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English', 'French'],
    services: ['Sports Injury Management', 'ACL Recovery Protocol', 'Joint Mobilisation', 'Post-Op Knee Rehab'],
    bio: 'Lead consultant musculoskeletal and sports physiotherapist with 15+ years treating premiership athletes, runners, and post-arthroscopic knee and shoulder surgical patients in Central London.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - King\'s College London', 'MSc Sports Medicine - University College London (UCL)'],
    feedback: [
      { rating: 5, comment: 'Alastair got me back into marathon training within 10 weeks of meniscus repair. Truly world-class.', user: 'Jonathan Davies' },
      { rating: 5, comment: 'Exceptional home visit in Canary Wharf, highly professional and thorough.', user: 'Sarah Jenkins' },
    ],
  },
  {
    id: 'th-uk-2',
    slug: 'ms-charlotte-sinclair',
    name: 'Ms. Charlotte Sinclair, MCSP',
    qualification: 'MSc Neurological Rehabilitation, MCSP, HCPC Reg.',
    specialization: 'Neurology',
    experience: '12 Years',
    city: 'London',
    state: 'Greater London',
    areas: ['Richmond', 'Wandsworth', 'Fulham', 'Kensington', 'Southwark', 'Greenwich', 'Hampstead'],
    rating: 4.9,
    reviewCount: 118,
    imageUrl: 'https://images.unsplash.com/photo-1594824813596-f94d9346d849?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Neuro Rehabilitation', 'Stroke Recovery', 'Parkinson Care', 'Multiple Sclerosis Rehab'],
    bio: 'Senior consultant neuro-physiotherapist with over 12 years of London teaching hospital and home care experience in neuromuscular re-education, stroke recovery, and gait retraining.',
    isVerified: true,
    education: ['MSc Neurological Rehabilitation - St George\'s University of London', 'BSc (Hons) Physiotherapy - Brunel University'],
    feedback: [
      { rating: 5, comment: 'Charlotte transformed my mother\'s mobility and confidence after her stroke. Highly empathetic.', user: 'Rupert Campbell' },
    ],
  },
  {
    id: 'th-uk-3',
    slug: 'mr-edward-davies',
    name: 'Mr. Edward Davies, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Spine & Pain Management',
    experience: '10 Years',
    city: 'London',
    state: 'Greater London',
    areas: ['Marylebone', 'Paddington', 'St John\'s Wood', 'Notting Hill', 'Ealing', 'Hammersmith'],
    rating: 4.8,
    reviewCount: 96,
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English', 'Welsh'],
    services: ['Spine Decompression', 'Sciatica Relief Protocol', 'Postural Ergonomics', 'Trigger Point Dry Needling'],
    bio: 'Specialist in complex lumbar spine, cervical nerve entrapment, and occupational posture correction for City and West End corporate executives.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - Cardiff University', 'Postgraduate Certificate in Spinal Manipulative Therapy'],
    feedback: [
      { rating: 5, comment: 'Severe desk-bound sciatica eliminated in 4 sessions. Cannot recommend him enough.', user: 'Alexandre Meyer' },
    ],
  },
  {
    id: 'th-uk-4',
    slug: 'mr-james-callum',
    name: 'Mr. James Callum, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Orthopedics',
    experience: '11 Years',
    city: 'Manchester',
    state: 'Greater Manchester',
    areas: ['Deansgate', 'Didsbury', 'Salford Quays', 'Altrincham', 'Chorlton', 'Sale', 'MediaCityUK'],
    rating: 4.9,
    reviewCount: 124,
    imageUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Post-Op Knee Replacement (TKR)', 'Total Hip Rehab (THR)', 'Rotator Cuff Conditioning', 'Manual Joint Therapy'],
    bio: 'Clinical Lead at our Manchester Deansgate centre, delivering structured post-surgical recovery and precision musculoskeletal manual therapy across Greater Manchester.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - University of Manchester', 'Certified Manual Therapist (MACP)'],
    feedback: [
      { rating: 5, comment: 'Superb rehabilitation following my total knee replacement. Walking without crutches well ahead of schedule.', user: 'Arthur Pendelton' },
    ],
  },
  {
    id: 'th-uk-5',
    slug: 'ms-fiona-macdougall',
    name: 'Ms. Fiona MacDougall, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Geriatrics & Mobility',
    experience: '14 Years',
    city: 'Edinburgh',
    state: 'Scotland',
    areas: ['New Town', 'Morningside', 'Stockbridge', 'Leith', 'Bruntsfield', 'Grange', 'City Centre'],
    rating: 4.9,
    reviewCount: 110,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Geriatric Balance & Fall Prevention', 'Bedridden Rehabilitation', 'Chest Physiotherapy', 'Stroke Recovery'],
    bio: 'Compassionate senior physiotherapist specializing in elderly mobility preservation, post-fall confidence restoration, and palliative gentle mobilization in Edinburgh homes.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - Queen Margaret University Edinburgh', 'Specialist Certification in Geriatric Assessment'],
    feedback: [
      { rating: 5, comment: 'Fiona helped my 84-year-old mother regain her balance and walk independently in the garden again.', user: 'Claire MacLeod' },
    ],
  },
  {
    id: 'th-uk-6',
    slug: 'mr-david-robertson',
    name: 'Mr. David Robertson, MCSP',
    qualification: 'MSc Musculoskeletal Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Orthopedics',
    experience: '13 Years',
    city: 'Glasgow',
    state: 'Scotland',
    areas: ['West End', 'Bearsden', 'Merchant City', 'Southside', 'Shawlands', 'Kelvinside'],
    rating: 4.8,
    reviewCount: 88,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Orthopedic Joint Mobilisation', 'Spine & Lumbar Care', 'Sports Conditioning', 'Post-Op Knee Rehab'],
    bio: 'Senior musculoskeletal clinician in Glasgow with extensive NHS and private practice background focusing on joint biomechanics and functional recovery.',
    isVerified: true,
    education: ['MSc Musculoskeletal Physiotherapy - Glasgow Caledonian University'],
    feedback: [
      { rating: 5, comment: 'David was fantastic with my shoulder impingement. Back to golf in under a month.', user: 'Gordon Stewart' },
    ],
  },
  {
    id: 'th-uk-7',
    slug: 'ms-sophie-turner',
    name: 'Ms. Sophie Turner, MCSP',
    qualification: 'BSc (Hons), PGCert Pelvic Health, MCSP, HCPC Reg.',
    specialization: "Women's Health",
    experience: '11 Years',
    city: 'Birmingham',
    state: 'West Midlands',
    areas: ['Edgbaston', 'Harborne', 'Solihull', 'Sutton Coldfield', 'Jewellery Quarter', 'Moseley'],
    rating: 4.9,
    reviewCount: 105,
    imageUrl: 'https://images.unsplash.com/photo-1594824813596-f94d9346d849?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Pelvic Floor Rehabilitation', 'Antenatal & Postnatal Care', 'Diastasis Recti Repair', 'Core Reconditioning'],
    bio: 'Specialist pelvic health and postnatal physiotherapist dedicated to helping mothers recover core stability, eliminate pelvic pain, and restore functional vitality.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - University of Birmingham', 'Postgraduate Certificate in Continence & Pelvic Health (POGP)'],
    feedback: [
      { rating: 5, comment: 'Invaluable postnatal support. Sophie made me feel completely comfortable and supported.', user: 'Emily Vance' },
    ],
  },
  {
    id: 'th-uk-8',
    slug: 'mr-oliver-bennett',
    name: 'Mr. Oliver Bennett, MCSP',
    qualification: 'MSc Sports & Exercise Medicine, MCSP, HCPC Reg.',
    specialization: 'Sports',
    experience: '9 Years',
    city: 'Bristol',
    state: 'South West',
    areas: ['Clifton', 'Redland', 'Harbourside', 'Cotham', 'Henleaze', 'Westbury-on-Trym'],
    rating: 4.9,
    reviewCount: 92,
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Athletic Performance Conditioning', 'Tendonopathy Protocols', 'ACL Rehabilitation', 'Manual Sports Therapy'],
    bio: 'Sports medicine and elite athletic conditioning physiotherapist serving runners, cyclists, and team sport athletes across Bristol.',
    isVerified: true,
    education: ['MSc Sports & Exercise Medicine - University of Bath', 'BSc (Hons) Physiotherapy - UWE Bristol'],
    feedback: [
      { rating: 5, comment: 'Fixed my chronic Achilles tendonitis when nothing else worked.', user: 'Marcus Thorne' },
    ],
  },
  {
    id: 'th-uk-9',
    slug: 'ms-rachel-harrison',
    name: 'Ms. Rachel Harrison, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Pediatrics',
    experience: '12 Years',
    city: 'Leeds',
    state: 'West Yorkshire',
    areas: ['Headingley', 'Roundhay', 'Chapel Allerton', 'Alwoodley', 'Horsforth', 'City Centre'],
    rating: 4.8,
    reviewCount: 84,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Developmental Milestone Delay', 'Cerebral Palsy Therapy', 'Paediatric Gait Retraining', 'Torticollis Correction'],
    bio: 'Gentle, play-based paediatric physical therapist supporting infants, children, and teens with congenital, neurological, and developmental motor challenges.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - University of Leeds', 'Member of Association of Paediatric Chartered Physiotherapists (APCP)'],
    feedback: [
      { rating: 5, comment: 'Wonderful rapport with our 5-year-old daughter. Her walking balance has improved immensely.', user: 'Hannah Briggs' },
    ],
  },
  {
    id: 'th-uk-10',
    slug: 'mr-gareth-evans',
    name: 'Mr. Gareth Evans, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Spine & Pain Management',
    experience: '14 Years',
    city: 'Cardiff',
    state: 'Wales',
    areas: ['Cardiff Bay', 'Pontcanna', 'Roath', 'Cyncoed', 'Penarth', 'Llandaff'],
    rating: 4.9,
    reviewCount: 98,
    imageUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English', 'Welsh'],
    services: ['Chronic Neck & Back Pain', 'Workplace Ergonomics', 'Post-Surgical Lumbar Rehab', 'Dry Needling'],
    bio: 'Lead spinal clinician in South Wales specializing in evidence-based non-surgical spinal recovery and occupational ergonomics.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - Cardiff University'],
    feedback: [
      { rating: 5, comment: 'Drastic improvement in lower back stiffness within just three home sessions in Pontcanna.', user: 'Gethin Morgan' },
    ],
  },
  {
    id: 'th-uk-11',
    slug: 'ms-ciara-murphy',
    name: 'Ms. Ciara Murphy, MCSP',
    qualification: 'BSc (Hons) Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Geriatrics & Mobility',
    experience: '10 Years',
    city: 'Belfast',
    state: 'Northern Ireland',
    areas: ['Malone Road', 'Lisburn Road', 'Titanic Quarter', 'Ballyhackamore', 'Stranmillis', 'City Centre'],
    rating: 4.8,
    reviewCount: 76,
    imageUrl: 'https://images.unsplash.com/photo-1594824813596-f94d9346d849?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English'],
    services: ['Fall Prevention & Gait Labs', 'Post-Hospital Discharge Rehab', 'Osteoarthritis Management', 'Home Exercise Plans'],
    bio: 'Dedicated community physiotherapist in Belfast focusing on elderly rehabilitation, joint mobility, and safe independent living at home.',
    isVerified: true,
    education: ['BSc (Hons) Physiotherapy - Ulster University'],
    feedback: [
      { rating: 5, comment: 'Ciara was so warm and encouraging with my dad after his hospital stay. Excellent care.', user: 'Patrick O\'Connor' },
    ],
  },
  {
    id: 'th-uk-12',
    slug: 'mr-thomas-clarke',
    name: 'Mr. Thomas Clarke, MCSP',
    qualification: 'MSc Advanced Manipulative Physiotherapy, MCSP, HCPC Reg.',
    specialization: 'Orthopedics',
    experience: '16 Years',
    city: 'London',
    state: 'Greater London',
    areas: ['Chelsea', 'Kensington', 'Fulham', 'Battersea', 'Clapham', 'Wandsworth'],
    rating: 4.9,
    reviewCount: 168,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    isAvailable: true,
    languages: ['English', 'German'],
    services: ['Advanced Manual Therapy', 'Spinal Manipulation', 'Complex Joint Rehabilitation', 'Second Opinion Diagnostics'],
    bio: 'Fellow of the Musculoskeletal Association of Chartered Physiotherapists (MACP) offering elite private home consultations across South-West London.',
    isVerified: true,
    education: ['MSc Advanced Manipulative Physiotherapy - University of Birmingham', 'BSc (Hons) Physiotherapy - King\'s College London'],
    feedback: [
      { rating: 5, comment: 'Thomas gave the most thorough clinical assessment I have ever had. Solved my hip problem within weeks.', user: 'Lady Eleanor Vance' },
    ],
  },
];
